# Permalinks
permalink:        pretty

# Setup
title:            '@faisalahsan'
tagline:          PHP, Javascript and Android fanatic, open source lover and tinkerer.
url:              http://faisalahsan.github.io
paginate:         1
baseurl:          ""
author:
  name:           Faisal
  url:            http://faisalahsan.github.io
  email:          faisalahsan.se@gmail.com
  github:         http://github.com/faisalahsan
  description:    'I am Faisal Ahsan, a full stack web and Android developer.'

# Custom vars
version:          0.0.1
github:
  repo:           http://github.com/faisalahsan/faisalahsan.github.io

# Menu
pages_list:       
  Archive: '/archive'
  About: '/about'
  Feed: '/atom.xml'

# Stay in touch
external_links:
  github: 'http://github.com/faisalahsan'
  mail: 'mailto:faisalahsan.se@gmail.com'
  linkedin: 'https://www.linkedin.com/in/faysalahsan/'

plugins:          [jekyll-paginate, rouge]
paginate:         10
paginate_path: "/blog/page:num"
highlighter: rouge